### PR TITLE
Added environment.yml file for conda installation.

### PR DESCRIPTION
**Pull request by dyvasey**
Hi Anne, I've added a fairly minimal conda installation file here, with just the packages we explicitly call and their versions. From what I've read, this is best practice for sharing conda environments since dependency requirements vary across platforms. Note that when I install from this file and then recreate a new pip requirements.txt file, there are a couple minor version changes to certain packages that have since been updated.

### CODE REVIEW

**Comment by anne-glerum** [comment]
Hi Dylan, thanks for adding the env file. I'll merge this, but I think it would be good if you also update the requirement.txt file so that both env files are the same.

**Comment by dyvasey** [comment]
Hi Anne - do you mean to simplify the pip requirements file so that it also specifies only the explicitly called packages (i.e., only lists numpy, pandas, pyvista, cmcrameri, etc.) or to update the minor version changes in dependencies I mentioned above? 

If I update the versions in requirements.txt, that may still not match the exact versions that someone will get if they install the environment.yml file because of variations across platforms and possible future updates in dependencies. On the other hand, I'm not sure if simplifying the pip requirements file is a good practice, since it handles dependencies differently from conda?

This has turned out to be much more complicated than I anticipated, and if it would simplify things, we could just stick with the original pip requirements.txt and not worry about conda at all (i.e., undo this pull request).

**Comment by anne-glerum** [comment]
Hi Dylan, sorry for being unclear. I meant updating the minor version changes, just so that at one moment in time we created the environment.yml and requirements.txt file at the same time from the same environment. However, if you do not see the benefit in that, then let's leave it at this. We'll see if any of the co-authors use the yml file. If not, we can always remove it later.

**Comment by dyvasey** [comment]
No worries, I'm starting to understand why people have such strong opinions about conda vs. pip. I'll leave as is for now and will develop in an environment using the current requirements.txt; we'll just have to be aware that if someone builds an environment from the yml file instead their dependencies will likely vary slightly. Hopefully that won't make a difference as long as the same versions of numpy, pyvista, etc. are used.

**Pull request merged**
